In [47]:
from re import T
import pandas as pd
import os
import numpy as np
import math

TEAM_NAMES = {'Canada': 'Olympic (Women) - Canada', 
              'USA': 'Olympic (Women) - United States',
              'Finland': 'Olympic (Women) - Finland',
              'ROC': 'Olympic (Women) - Olympic Athletes from Russia',
              'Switzerland': 'Olympic (Women) - Switzerland'}

In [48]:
os.chdir('C:/Users/Paula/Desktop/Big-Data-Cup-2022-Private')

In [49]:
game = '2022-02-08 Canada at USA'
pp = '2022-02-08 Canada at USA P1 PP1.csv'
location = "data/"+game+"/"+pp
MAX_FRAME_JUMP = 5

In [50]:
def get_names_date(game):
    spl = game.split(' ')
    date_comps = spl[0].split('-')
    date = '{}/{}/{}'.format(*[dt.strip('0') for dt in date_comps[::-1]])
    team_1 = TEAM_NAMES[spl[1]]
    team_2 = TEAM_NAMES[spl[3]]
    
    return team_1, team_2, date
    
def get_speed(track):
    assert (track['track_id'] == track['track_id'].iloc[0]).all()
    try:
        frame_diff = np.diff(track['frame_id'])
        nonvalid_speed = np.concatenate([[True],frame_diff>MAX_FRAME_JUMP])
        next_valid_speed = np.concatenate([frame_diff<=MAX_FRAME_JUMP,[False]])
        repl = nonvalid_speed & next_valid_speed
        idx = np.where(repl)[0]+1
        
        x_spd = np.concatenate([[np.nan],np.diff(track['x_ft'])/frame_diff])*30
        y_spd = np.concatenate([[np.nan],np.diff(track['y_ft'])/frame_diff])*30
        
        x_spd[repl] = x_spd[idx]
        y_spd[repl] = y_spd[idx]

    except Exception as e:
        print(np.diff(track['frame_id']))
        raise

    return(x_spd, y_spd)

In [76]:
def get_pp_tracking(power_play_info_file = 'pp_info.csv',
    play_by_play_data_file = 'pxp_womens_oly_2022_v2.csv',
    tracking_dir = 'data',
    pbp_dir = 'data'):

    play_by_play_data = pd.read_csv(os.path.join(tracking_dir,play_by_play_data_file))
    power_play_info = pd.read_csv(os.path.join(pbp_dir,power_play_info_file))

    #power_play_info['game_name'].loc[power_play_info['game_name']=='2022-02-14 USA at Finland'] = '2022-02-14 Finland at USA'
    power_play_info['relevant_events'] = np.nan

    relevant_eventses = []
    for ix, pp in power_play_info.iterrows():
        relevant_events = None
        game = pp['game_name']
        print(game)
        #if game!='2022-02-14 Finland at USA':
        game_files = os.listdir(os.path.join(tracking_dir,game))
        tracking_data_name = os.path.join(tracking_dir,game,f'{game} P{pp["start_period"]} PP{pp["penalty_number"]}.csv')
        tracking_info_name = os.path.join(tracking_dir,game,f'videoShotsInfo_{game} P{pp["start_period"]} PP{pp["penalty_number"]}.csv')
        roster_info_name = os.path.join(tracking_dir, game, f'{game} roster.csv')
        roster_info = pd.read_csv(roster_info_name, index_col = 0)
        if os.path.split(tracking_data_name)[1] in game_files:
            tracking_data = pd.read_csv(tracking_data_name)
            #tracking_data['x_ft'] = tracking_data['x_ft'] - 7
            #tracking_data['y_ft'] = tracking_data['y_ft'] + 4

            tracking_data['vel_x'] = np.nan
            tracking_data['vel_y'] = np.nan
            tracking_data['angle'] = np.nan
            tr_ids = tracking_data.track_id.unique()
            for tr_id in tr_ids:
                idxs = tracking_data.track_id==tr_id
                track = tracking_data.loc[idxs]
                if len(track) <= 5:
                    continue
                x_spd,y_spd = get_speed(track)
                tracking_data.loc[idxs,'vel_x'] = x_spd
                tracking_data.loc[idxs,'vel_y'] = y_spd
                tracking_data['angle'] = np.arctan2(tracking_data['vel_y'],tracking_data['vel_x'])
            tracking_info = pd.read_csv(tracking_info_name)
        else:
            print('Tracking file missing:\n{}'.format(tracking_data_name))
            relevant_eventses.append(None)
            continue
        team_1, team_2, date = get_names_date(game)
        # print('{}\n{}\n{}\n'.format(team_1,team_2,date))
        relevant_events = play_by_play_data.loc[(play_by_play_data['game_date'] == date) & 
                                    ((play_by_play_data['team_name'] == team_1) |
                                        (play_by_play_data['team_name'] == team_2))]

        relevant_events = relevant_events.loc[((relevant_events['period']>= pp['start_period']) 
                                                & (relevant_events['clock_seconds'] <= pp['start_game_clock_seconds'])) &
                                              ((relevant_events['period']<= pp['end_period']) & 
                                              (relevant_events['clock_seconds'] >= pp['end_game_clock_seconds']))  ]


        relevant_events.index = np.arange(0, len(relevant_events.index), dtype = 'int')

        pl1_jn = roster_info.loc[relevant_events['player_name'],'jn']
        pl1_jn.index = relevant_events.index

        pl2_exists = list(relevant_events['player_name_2'].notna())
        pl2_jn = roster_info.loc[relevant_events['player_name_2'][pl2_exists],'jn']

        pl2_jn.index = relevant_events.index[pl2_exists]
        relevant_events['Player_1_num'] = pl1_jn
        relevant_events['Player_2_num'] = pl2_jn

        tracks = []
        ### Continue from here - need to check if there is a next event
        for rw, event in relevant_events.iterrows():
            rel_shot = 0
            time_bonus = 0 if event['period'] == pp['start_period'] else 1200
            event_frame_time = (pp['start_game_clock_seconds'] - event['clock_seconds'] + time_bonus)*30.0 - 15
            # print(len(relevant_events), rw)
            if rw < (len(relevant_events)-1):
                time_bonus = 0 if relevant_events.loc[rw+1,'period'] == pp['start_period'] else 1200
                next_event_frame_time = (pp['start_game_clock_seconds'] - relevant_events.loc[rw+1,'clock_seconds'] + time_bonus)*30.0 + 15
            else:
                next_event_frame_time = 10000000
            # print(event_frame_time, next_event_frame_time)
            # assert False
            while rel_shot<len(tracking_info.index):
                # print(tracking_info)
                if event_frame_time >= tracking_info.loc[rel_shot,'frame_start_shot']:
                    if event_frame_time >= tracking_info.loc[rel_shot,'frame_end_shot']:
                        rel_shot+=1
                        if rel_shot==len(tracking_info.index):
                            tracks.append(None)
                    else:
                        tracks.append(tracking_data.loc[(tracking_data['frame_id']>=(event_frame_time)) &
                                                     (tracking_data['frame_id']<(next_event_frame_time))])
                        break

                elif next_event_frame_time > tracking_info.loc[rel_shot,'frame_start_shot']:
                    tracks.append(tracking_data.loc[tracking_data['frame_id']<(next_event_frame_time)])
                    break
                else:
                    tracks.append(None)
                    break
        relevant_events['tracks'] = tracks

        relevant_eventses.append(relevant_events)
    power_play_info['relevant_events'] = relevant_eventses
    return power_play_info

In [77]:
relevant_events = get_pp_tracking()
relevant_events.head()

2022-02-08 Canada at USA
2022-02-08 Canada at USA
2022-02-08 Canada at USA
2022-02-08 Canada at USA
Tracking file missing:
data\2022-02-08 Canada at USA\2022-02-08 Canada at USA P2 PP4.csv
2022-02-08 Canada at USA
2022-02-08 Canada at USA
2022-02-08 Canada at USA
2022-02-08 ROC at Finland
2022-02-08 ROC at Finland
2022-02-08 ROC at Finland
Tracking file missing:
data\2022-02-08 ROC at Finland\2022-02-08 ROC at Finland P2 PP3.csv
2022-02-08 ROC at Finland
Tracking file missing:
data\2022-02-08 ROC at Finland\2022-02-08 ROC at Finland P2 PP4.csv
2022-02-08 ROC at Finland
2022-02-08 ROC at Finland
2022-02-12 Switzerland at ROC
2022-02-12 Switzerland at ROC
2022-02-12 Switzerland at ROC
2022-02-12 Switzerland at ROC
Tracking file missing:
data\2022-02-12 Switzerland at ROC\2022-02-12 Switzerland at ROC P3 PP4.csv
2022-02-12 Switzerland at ROC
2022-02-14 Switzerland at Canada
2022-02-14 Switzerland at Canada
2022-02-14 Switzerland at Canada
Tracking file missing:
data\2022-02-14 Switzerland at Canada\2022-02-14 Switzerland at Canada P2 PP3.csv
2022-02-14 Switzerland at Canada
2022-02-14 Switzerland at Canada
2022-02-14 USA at Finland
2022-02-14 USA at Finland
Tracking file missing:
data\2022-02-14 USA at Finland\2022-02-14 USA at Finland P2 PP2.csv
2022-02-14 USA at Finland
2022-02-14 USA at Finland
2022-02-14 USA at Finland
2022-02-14 USA at Finland
Tracking file missing:
data\2022-02-14 USA at Finland\2022-02-14 USA at Finland P3 PP6.csv
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland
Tracking file missing:
data\2022-02-16 Switzerland at Finland\2022-02-16 Switzerland at Finland P1 PP3.csv
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland
2022-02-16 Switzerland at Finland

,game_name,penalty_number,start_video_clock_seconds,end_video_clock_seconds,start_period,end_period,start_game_clock_seconds,end_game_clock_seconds,relevant_events
0,2022-02-08 Canada at USA,1,1278,1314,1,1,386,350,game_date season_year ...
1,2022-02-08 Canada at USA,2,1624,1744,1,1,216,96,game_date season_year ...
2,2022-02-08 Canada at USA,3,409,562,2,2,991,871,game_date season_year ...
3,2022-02-08 Canada at USA,4,898,898,2,2,613,613,None
4,2022-02-08 Canada at USA,5,1690,1927,2,2,272,152,game_date season_year ...

In [78]:
relevant_events.loc[0,'relevant_events'].head()

,game_date,season_year,team_name,opp_team_name,venue,period,clock_seconds,situation_type,goals_for,goals_against,...,x_coord_2,y_coord_2,event_detail_1,event_detail_2,event_detail_3,frame_id_1,frame_id_2,Player_1_num,Player_2_num,tracks
0,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,386,5 on 5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,10.0,NaN
1,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,386,4 on 5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,29.0,NaN
2,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,383,4 on 5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,382,4 on 5,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
4,8/2/2022,2021,Olympic (Women) - Canada,Olympic (Women) - United States,away,1,380,5 on 4,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,NaN,NaN

In [79]:
relevant_events.loc[0,'relevant_events'].tracks.iloc[6]

,frame_id,period,track_id,team_id,team_name,jersey_number,x_ft,y_ft,video_shot,game_seconds,vel_x,vel_y,angle
98,315,1,1,Light,Canada,6,166.412354,46.525812,1,376,5.482728,8.911096,1.019225
99,315,1,2,Dark,USA,2,183.106257,40.074749,1,376,-6.806727,4.755684,2.531757
100,315,1,3,Dark,USA,35,187.198140,43.961487,1,376,1.554063,0.914565,0.531920
101,315,1,4,Light,Canada,19,195.635778,65.999070,1,376,2.143761,1.141240,0.489195
102,315,1,5,Dark,USA,28,166.892413,38.917458,1,376,2.140944,8.115468,1.312863
...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,404,1,4,Light,Canada,19,182.150170,61.593181,1,373,0.244986,-11.055250,-1.548640
822,404,1,7,Dark,USA,5,173.488274,59.395426,1,373,-1.012683,3.871421,1.826643
823,404,1,2,Dark,USA,2,175.493738,44.706158,1,373,1.527054,-6.361436,-1.335205
824,404,1,5,Dark,USA,28,161.507374,47.719855,1,373,0.551709,5.255918,1.466210
825,404,1,9,Light,Canada,23,129.664039,35.691163,1,373,2.313942,5.636799,1.181266

In [81]:
relevant_events.to_json(r'data/BDC_2022_all_data.json')