# Reading events from PPs and adding Tracking

Currently the code will read the PPs from the pp_info.csv file, then it will find relevant events from the event file that match. After that it will attempt to get tracking data that is relevant. 

First it will figure out the time of the event relevant to the frame time of the tracking info (use the videoShotsInfo files). Then it will assign each file with the tracking data between it and then next event. In order to avoid events that are close together not getting any tracking at all I assign 15 frames back and 15 forward to each event just in case (1 second extra tracking), this also accounts for the limited granularity in the event timing (which is 1 sec vs 30 fps for tracking)

Tracking data is corrected as per the tweet we found, but not doing anything about gaps or about "player 100s"

I am not saving it at the moment because it is nested and doesn't take long to run.

In [1]:
from read_and_join_events_tracking import *
import os

# print(os.path.join('../','pxp_womens_oly_2022_v2.csv'))

relevant_events = get_pp_tracking(tracking_dir='./', pbp_dir = '../')

C:\Users\Paula\anaconda3\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

Tracking file missing:
./2022-02-08 Canada at USA\2022-02-08 Canada at USA P2 PP4.csv
Tracking file missing:
./2022-02-12 Switzerland at ROC\2022-02-12 Switzerland at ROC P3 PP4.csv
Tracking file missing:
./2022-02-14 Switzerland at Canada\2022-02-14 Switzerland at Canada P2 PP3.csv
Tracking file missing:
./2022-02-14 Finland at USA\2022-02-14 Finland at USA P2 PP2.csv
Tracking file missing:
./2022-02-16 Switzerland at Finland\2022-02-16 Switzerland at Finland P1 PP3.csv

#Example of the format of the output:

A dataframe containing each PP, with a column named "relevant_events" which contains a DF with event data

In [3]:
relevant_events.head()

,game_name,penalty_number,start_video_clock_seconds,end_video_clock_seconds,start_period,end_period,start_game_clock_seconds,end_game_clock_seconds,relevant_events
0,2022-02-08 Canada at USA,1,1278,1314,1,1,386,350,game_date season_year ...
1,2022-02-08 Canada at USA,2,1624,1744,1,1,216,96,game_date season_year ...
2,2022-02-08 Canada at USA,3,409,562,2,2,991,871,game_date season_year ...
3,2022-02-08 Canada at USA,4,898,898,2,2,613,613,None
4,2022-02-08 Canada at USA,5,1690,1927,2,2,272,152,game_date season_year ...

Example of one DF of event data, which contains a column of tracking data called "tracks", which itself is a DF

In [4]:
relevant_events.loc[0,'relevant_events'].head()

,game_date,season_year,team_name,opp_team_name,venue,period,clock_seconds,situation_type,goals_for,goals_against,...,x_coord,y_coord,event_type,player_name_2,x_coord_2,y_coord_2,event_detail_1,event_detail_2,event_detail_3,tracks
0,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,386,5 on 5,0,0,...,5,67,Cross-checking,Sarah Fillier,NaN,NaN,NaN,NaN,NaN,None
1,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,386,4 on 5,0,0,...,31,65,Backhand,Marie-Philip Poulin,NaN,NaN,NaN,NaN,NaN,None
2,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,383,4 on 5,0,0,...,6,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,8/2/2022,2021,Olympic (Women) - United States,Olympic (Women) - Canada,home,1,382,4 on 5,0,0,...,4,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,8/2/2022,2021,Olympic (Women) - Canada,Olympic (Women) - United States,away,1,380,5 on 4,0,0,...,165,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

Finally, an example of one DF of tracking data

In [5]:
relevant_events.loc[0,'relevant_events'].tracks.iloc[6]

,frame_id,period,track_id,team_id,team_name,jersey_number,x_ft,y_ft
98,315,1,1,Light,Canada,6,54.525812,50.525812
99,315,1,2,Dark,USA,2,48.074749,44.074749
100,315,1,3,Dark,USA,37,51.961487,47.961487
101,315,1,4,Light,Canada,11,73.999070,69.999070
102,315,1,5,Dark,USA,28,46.917458,42.917458
...,...,...,...,...,...,...,...,...
805,404,1,13,Light,Canada,100,82.385167,78.385167
806,404,1,16,Light,Canada,6,64.552903,60.552903
807,404,1,18,Dark,USA,3,55.444952,51.444952
808,404,1,7,Dark,USA,5,67.395426,63.395426
809,404,1,22,Dark,USA,10,44.093598,40.093598

In [ ]:
relevant_events